// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7v08wKvzbw0EHy0thSTc0twBGFiA0iM',
    appId: '1:1022978771153:web:df5d8554a11479c2fa5df0',
    messagingSenderId: '1022978771153',
    projectId: 'ai-video-d-zenleme',
    authDomain: 'ai-video-d-zenleme.firebaseapp.com',
    storageBucket: 'ai-video-d-zenleme.firebasestorage.app',
    measurementId: 'G-JDQQ3JR1GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAUtr9oKSVe0QoT57yRdwxFzi6UjDwQsQ',
    appId: '1:1022978771153:android:c0a95be0c66b868bfa5df0',
    messagingSenderId: '1022978771153',
    projectId: 'ai-video-d-zenleme',
    storageBucket: 'ai-video-d-zenleme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihScAtnoWb46XM65FBlr6imODQKKfQ40',
    appId: '1:1022978771153:ios:369bc2dbf3aa17f1fa5df0',
    messagingSenderId: '1022978771153',
    projectId: 'ai-video-d-zenleme',
    storageBucket: 'ai-video-d-zenleme.firebasestorage.app',
    iosBundleId: 'com.example.aiVideoYapma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihScAtnoWb46XM65FBlr6imODQKKfQ40',
    appId: '1:1022978771153:ios:369bc2dbf3aa17f1fa5df0',
    messagingSenderId: '1022978771153',
    projectId: 'ai-video-d-zenleme',
    storageBucket: 'ai-video-d-zenleme.firebasestorage.app',
    iosBundleId: 'com.example.aiVideoYapma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7v08wKvzbw0EHy0thSTc0twBGFiA0iM',
    appId: '1:1022978771153:web:4dd877dcdaff552cfa5df0',
    messagingSenderId: '1022978771153',
    projectId: 'ai-video-d-zenleme',
    authDomain: 'ai-video-d-zenleme.firebaseapp.com',
    storageBucket: 'ai-video-d-zenleme.firebasestorage.app',
    measurementId: 'G-JYFMPMSS60',
  );
}
